# Generated by Django 4.2.2 on 2024-11-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_nick',
            field=models.CharField(max_length=50, unique=True, verbose_name='Телеграмм ник'),
        ),
    ]
