# Generated by Django 4.2.2 on 2024-11-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_tg_nick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tg_nick',
        ),
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(default='нет_телеграмма', max_length=50, unique=True, verbose_name='Телеграмм chat_id'),
        ),
    ]
