# Generated by Django 4.2.2 on 2024-10-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='название полезной привычки')),
                ('place', models.CharField(max_length=35, verbose_name='название места')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=50, verbose_name='название действия')),
                ('pleasant_habit', models.CharField(max_length=50, verbose_name='название приятной привычки')),
                ('award', models.CharField(max_length=50, verbose_name='Вознаграждение за выполнение полезной привычки')),
                ('sign_publicity', models.CharField(choices=[('public', 'Публичная'), ('non-public', 'Непубличная')], max_length=50, verbose_name='Публичная полезная привычка или нет?')),
            ],
            options={
                'verbose_name': 'Полезная привычка',
                'verbose_name_plural': 'Полезные привычки',
            },
        ),
    ]
