# Generated by Django 4.2.2 on 2024-10-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulhabit',
            name='award',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вознаграждение за выполнение полезной привычки'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='pleasant_habit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='название приятной привычки'),
        ),
    ]
