# Generated by Django 4.2.2 on 2024-10-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_usefulhabit_award_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefulhabit',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], null=True, verbose_name='День недели'),
        ),
    ]
