# Generated by Django 4.2.2 on 2024-11-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_usefulhabit_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefulhabit',
            name='time_to_complete',
            field=models.PositiveIntegerField(default=120, verbose_name='Время на выполнение полезной привычки'),
        ),
    ]
