# Generated by Django 4.2.2 on 2024-11-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_usefulhabit_time_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulhabit',
            name='time_to_complete',
            field=models.PositiveIntegerField(default=120, verbose_name='Время на выполнение в секундах'),
        ),
    ]
