# Generated by Django 4.2.2 on 2024-11-05 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0008_pleasanthabit_alter_usefulhabit_pleasant_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pleasanthabit',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_pleasant_habit', to=settings.AUTH_USER_MODEL, verbose_name='Создатель приятной привычки'),
        ),
    ]
