# Generated by Django 4.2.2 on 2024-11-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_pleasanthabit_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pleasanthabit',
            options={'verbose_name': 'Приятная  привычка', 'verbose_name_plural': 'Приятные привычки'},
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='sign_publicity',
            field=models.BooleanField(verbose_name='Публичная полезная привычка или нет'),
        ),
    ]
